# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"
services:
  
  todoit-db:
    build: ./db/docker
    restart: always
    ports:
      - 5100:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: HelloW0rld
      MSSQL_DB: Todoit
      DATABASE_CONNECTION_STRING: "Server=todoit-db,5200;Database=Todoit;User Id=sa;Password=HelloW0rld;"
  
    volumes:
      - ./db/data:/var/opt/mssql/data
      
  api:
    image: mrbacky/todoitapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - todoit-db
    ports:
      - 5200:80

  flyway:
    image: flyway/flyway
    command: migrate
    volumes:
      - ./db:/flyway/sql
      - ./db:/flyway/conf
    depends_on:
      - todoit-db
